apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spark-substrait-gateway.fullname" . }}-secret
  labels:
    {{- include "spark-substrait-gateway.labels" . | nindent 4 }}
type: Opaque
data:
{{ (.Files.Glob "secrets/opaque/*").AsSecrets | indent 2 }}
