# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spark-substrait-gateway.fullname" . }}-tls-secret
  labels:
    {{- include "spark-substrait-gateway.labels" . | nindent 4 }}
type: Opaque
data:
{{ (.Files.Glob "secrets/tls/*").AsSecrets | indent 2 }}
