# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spark/connect/common.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aspark/connect/common.proto\x12\rspark.connect\"u\n\x0cStorageLevel\x12\x10\n\x08use_disk\x18\x01 \x01(\x08\x12\x12\n\nuse_memory\x18\x02 \x01(\x08\x12\x14\n\x0cuse_off_heap\x18\x03 \x01(\x08\x12\x14\n\x0c\x64\x65serialized\x18\x04 \x01(\x08\x12\x13\n\x0breplication\x18\x05 \x01(\x05\"6\n\x13ResourceInformation\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\taddresses\x18\x02 \x03(\tB6\n\x1eorg.apache.spark.connect.protoP\x01Z\x12internal/generatedb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spark.connect.common_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036org.apache.spark.connect.protoP\001Z\022internal/generated'
  _globals['_STORAGELEVEL']._serialized_start=45
  _globals['_STORAGELEVEL']._serialized_end=162
  _globals['_RESOURCEINFORMATION']._serialized_start=164
  _globals['_RESOURCEINFORMATION']._serialized_end=218
# @@protoc_insertion_point(module_scope)
